saltstack-formulas/tomcat-formula

tomcat/config.sls, tomcat/files/server.xml
https://tomcat.apache.org/tomcat-8.0-doc/changelog.html
With that line enabled, tomcat8 fails to start. Added another accumulator, following the example of `200_server_xml`, to enable/disable that line conditionally on version < 8.
=> Remove Jasper listener in tomcat>=8, add some comments to server.xml

.kitchen.yml, README.rst, pillar.example, test/integration/tomcat_config/serverspec/tomcat_config_spec.rb, test/integration/tomcat_install/serverspec/install_spec.rb, tomcat/config.sls, tomcat/defaults.yaml, tomcat/files/server.xml
`connectors`, in the `server.xml` file might be specified multiple times. The way it was declared, was allowing only one specification of it. Modified it to be a dict following the same logic as `sites`. This change is backward incompatible, as requires to reformat the `connector` -> `connectors` entry in the pillar.
Modified the defaults to be empty, so the default entries in `server.xml` are used (which, ideally, should be the same as in a default installation). Otherwise, those never were used.
Fixed tests and README, to match these new changes.
=> Allow specifiying multiple connectors in server.xml

tomcat/files/server.xml
With current code, when you don't define any valve for a site you'll get an error. 
This simple fix allows you to define a site without any valve.
=> Fix valves in server.xml template.

pillar.example
PR #42 reformatted `connector` -> `connectors` in the pillar, but the `pillar.example` file was not updated to reflect this change.  This fixes it.
=> connector -> connectors fix for pillar.example

tomcat/native.sls
This fixes #57.
lrwxrwxrwx 1 root root 23 Dec 25  2013 /usr/lib/x86_64-linux-gnu/libtcnative-1.so.0 -> libtcnative-1.so.0.1.29
lrwxrwxrwx 1 root root 42 Apr 11 10:39 /usr/lib/libtcnative-1.so -> /usr/lib/x86_64-linux-gnu/libtcnative-1.so
=> Fix tomcat.native symlink on Trusty

tomcat/files/tomcat-default-CentOS.template
RHEL7 and Tomcat7's preamble seems to have changed CLASSPATH munging from RHEL5+6, so you can no longer put the classpath inside the environmental variable JAVA_OPTS
I figured out how to fix my issue, and here is how to fix it for others in the salt community.
Addresses this issue:
https://github.com/saltstack-formulas/tomcat-formula/issues/59
=> Classpath Munging Change

pillar.example, tomcat/context.sls, tomcat/files/context.xml
- add ability to define context directives per path, not just within context.xml for the global scope.
- backwards compatible
- add new contexts via `other_contexts` declaration in pillar.
=> add ability to define context directive per path

pillar.example, tomcat/osmap.yaml
This PR replaces #64 due to rebase, etc.
The pillar.example is updated to defined hostname and hostname_id values from grains and also set fix the undefined {{ id }} reference.  example.com and example.net are converted to variables.
Fixes #64 
This osmap.yaml is updated to support OpenSUSE:
Fixes #62 
Installation successfully tested on OpenSUSE LEAP (4.2) server and Ubuntu 17.04
=> Resolve issue 62 (osmap.yaml) and 63 (pillar.example vars)

tomcat/manager.sls
This PR resolves #67.  Archlinux derivatives use pacman and archlinux packaging so tomcat.manager state must check `grains.os_family == Arch` because 'grains.os == Arch' is too specific.   
Test successfully on Manjaro: [tomcat_manjaro_testresult.log.txt](https://github.com/saltstack-formulas/tomcat-formula/files/1347216/tomcat_manjaro_testresult.log.txt)
=> Fix tomcat.manager state for Archlinux family to resolve #67

pillar.example, tomcat/defaults.yaml, tomcat/osmap.yaml
The purpose of this pull request is to consolidate *some* formula defaults across defaults.yaml, osmap.yaml and pillar.example files in the formula and add MacOS support to osmapping.  
The following are addressed by the PR.
1. pillar.example defines "override" values missing elsewhere in formula (i.e. defaults.yaml), going against good practice of reserving pillars for overrides.  This PR moves *some* to defaults.yaml because formula relies too heavily on pillars for some states.
- Moved the `pillar.example.tomcat.Catalina_xxxx` variables to defaults.yaml
- Moved `jvm_tmp`
- Few others (see diff).
2. pillar.example defines some dummy values which corrupt / fail the installation if naively reused.
- Section `tomcat.java_opts` has dummy path.
- Pillar`tomcat.connectors.keystore` has dummy …
=> Consolidate 'defaults' in Formula: Fixes and improvements

tomcat/cluster.sls
The tomcat.cluster.600_server_xml state fails on MacOS.  This PR excludes this state on MacOS.
Verified on following (Salt 2017 mostly, Suse has Salt 2016).
[tomcat_on_Darwin_verified (1).txt](https://github.com/saltstack-formulas/tomcat-formula/files/1357620/tomcat_on_Darwin_verified.1.txt)
[manjaro_tomcat_result.log.txt](https://github.com/saltstack-formulas/tomcat-formula/files/1357614/manjaro_tomcat_result.log.txt)
[ubuntu_tomcat_results.log.txt](https://github.com/saltstack-formulas/tomcat-formula/files/1357615/ubuntu_tomcat_results.log.txt)
[suse_tomcat_resultt.log.txt](https://github.com/saltstack-formulas/tomcat-formula/files/1357616/suse_tomcat_resultt.log.txt)
[centos7_tomcat_result.log.txt](https://github.com/saltstack-formulas/tomcat-formula/files/1357617/centos7_tomcat_result. …
=> Enhance tomcat.cluster state for MacOS

tomcat/config.sls, tomcat/files/limit.maxfiles.plist
This pull request is an enhancement for the tomcat.config state, introducing full MacOS support.
Verified on following (Salt 2017 mostly, Suse has Salt 2016).
[tomcat_on_Darwin_verified (1).txt](https://github.com/saltstack-formulas/tomcat-formula/files/1357620/tomcat_on_Darwin_verified.1.txt)
[manjaro_tomcat_result.log.txt](https://github.com/saltstack-formulas/tomcat-formula/files/1357614/manjaro_tomcat_result.log.txt)
[ubuntu_tomcat_results.log.txt](https://github.com/saltstack-formulas/tomcat-formula/files/1357615/ubuntu_tomcat_results.log.txt)
[suse_tomcat_resultt.log.txt](https://github.com/saltstack-formulas/tomcat-formula/files/1357616/suse_tomcat_resultt.log.txt)
[centos7_tomcat_result.log.txt](https://github.com/saltstack-formulas/tomcat-formula/files/1357617/centos7_tomcat_resul …
=> Enhance tomcat.config state with MacOS support

tomcat/init.sls
This pull request enhances the tomcat.init state to introduce full MacOS support for Tomcat package from Homebrew (and tap/homebrew-services) solutions.  Integration with Launchd is introduced.
Verified on following (Salt 2017 mostly, Suse has Salt 2016).
[tomcat_on_Darwin_verified (1).txt](https://github.com/saltstack-formulas/tomcat-formula/files/1357620/tomcat_on_Darwin_verified.1.txt)
[manjaro_tomcat_result.log.txt](https://github.com/saltstack-formulas/tomcat-formula/files/1357614/manjaro_tomcat_result.log.txt)
[ubuntu_tomcat_results.log.txt](https://github.com/saltstack-formulas/tomcat-formula/files/1357615/ubuntu_tomcat_results.log.txt)
[suse_tomcat_resultt.log.txt](https://github.com/saltstack-formulas/tomcat-formula/files/1357616/suse_tomcat_resultt.log.txt) …
=> Enhance tomcat state, Add MacOS & launchd support

tomcat/manager.sls
This PR introduces MacOS support for the tomcat.manage state.  Today this state fails because there is no `manager_pkg` candidate for Homebrew tomcat.
Verified on following (Salt 2017 mostly, Suse has Salt 2016).
[tomcat_on_Darwin_verified (1).txt](https://github.com/saltstack-formulas/tomcat-formula/files/1357620/tomcat_on_Darwin_verified.1.txt)
[manjaro_tomcat_result.log.txt](https://github.com/saltstack-formulas/tomcat-formula/files/1357614/manjaro_tomcat_result.log.txt)
[ubuntu_tomcat_results.log.txt](https://github.com/saltstack-formulas/tomcat-formula/files/1357615/ubuntu_tomcat_results.log.txt)
[suse_tomcat_resultt.log.txt](https://github.com/saltstack-formulas/tomcat-formula/files/1357616/suse_tomcat_resultt.log.txt)
[centos7_tomcat_result.log.txt](https://github.com/saltstack-form …
=> Add MacOS support for tomcat.manage.state

tomcat/osmap.yaml
This pull request sets 'ver: 8' for Suse family in osmap.yaml to resolve issue #78
=> Fix tomcat.config state on Suse

tomcat/cluster.sls, tomcat/config.sls, tomcat/manager.sls
This PR uses `unless` and `onlyif` instead of Jinja for few states as good practice.
The requisite check is primitive syntax for shell portability (sh/ksh/bash/zsh/etc).
```
[INFO    ] Executing state file.managed for [/Library/LaunchDaemons/limit.maxfiles.plist]
[DEBUG   ] Could not LazyLoad file.mod_run_check: 'file.mod_run_check' is not available.
[INFO    ] Executing command 'test "`uname`" = "FreeBSD"' in directory '/Users/xxxxx'
[DEBUG   ] output: 
[DEBUG   ] Last command return code: 1
[INFO    ] Executing state file.managed for [/usr/local/opt/tomcat/libexec/conf/tomcat-users.xml]
[DEBUG   ] Could not LazyLoad file.mod_run_check: 'file.mod_run_check' is not available.
[INFO    ] Executing command 'test "`uname`" = "FreeBSD"' in directory '/Users/xxxxx'
[DEBUG   ] output: 
[DEBUG …
```
=> Minor Jinja cleanup - Use unless/onlyif where possible

tomcat/config.sls, tomcat/context.sls, tomcat/manager.sls
This takes a conservative approach to implementing the changes I recommended in #89: I have only patched instances where I know the data structures being rendered are dictionary types.
Note that I am personally unable to test the changes to `context.sls` or `manager.sls`.
=> Fix YAML parse errors due to broken dictionary serialization

tomcat/init.sls
This PR attempts to fix tomcat state failures on MacOS. 
After completion of the `pkg.installed` state (`brew install`) a required service file is missing.
```
ID: tomcat
Function: file.managed
Name: /Library/LaunchAgents/homebrew.mxcl.tomcat.plist
Result: False
Comment: Local file source /usr/local/opt/tomcat/homebrew.mxcl.tomcat.plist does not exist
```
Manual troubleshooting gave a solution which this commit automates. 
```
$ brew install tomcat
Warning: tomcat 9.0.11 is already installed, it's just not linked
You can use `brew link tomcat` to link this version.
Error: /usr/local/opt/tomcat is not a valid keg
mac~ messi$ brew link tomcat
Linking /usr/local/Cellar/tomcat/9.0.11... Error: Directory not empty @ dir_s_rmdir - /usr/local/opt/tomcat
$ cd /usr/local/opt/ && mv tomcat …
```
=> Fix state failure(s) macOS

tomcat/init.sls, tomcat/osmap.yaml
This PR fixes failed state caused by running `cmd.run: brew ...` as root.
```
Retcode: 1 Error: Running Homebrew as root is extremely dangerous and no longer supported.
```
Instead command should run as the system user (i.e. not root).  Verified on MacOS.
=> run brew command as unprivledged user

pillar.example, test/integration/tomcat_install/serverspec/install_spec.rb, tomcat/clean.sls, tomcat/cluster.sls, tomcat/config.sls, tomcat/context.sls, tomcat/defaults.yaml, tomcat/expires.sls, tomcat/init.sls, tomcat/manager.sls, tomcat/native.sls, tomcat/vhosts.sls
This PR has few fixes and improvements.
**Fixes**
1. Tomcat 9 has no plist file causing lots of failed states on MacOS.  i.e. Error: /usr/local/opt/tomcat is not a valid keg" and `brew doctor`  issues
**Improved**
a. Added a clean state (removal)
b. Prefixed all states with "tomcat " to reduce risk of name collisions.
c. Updated Travis CI adding Ubuntu 18.40
c. removed useless check_service state
=> Fixes for MacOS and few improvements

pillar.example, tomcat/files/tomcat-users.xml
* Remove empty lines in generated files, between `roles`, and between `users`
* Allow `roles` to be a list
=> Tomcat users

tomcat/files/tomcat-default-Debian.template
Debian defines some defaults (which don't work here, not sure why).
Defaults were checked as `is defined`, which cannot be `undefined` via `lookup`.
* Added `JAVA_HOME` as optional
* Replaced `is defined` by checking for non-empty/false value
* Reformated for empty line in generated file
=> Debian etc default

pillar.example, tomcat/clean.sls, tomcat/defaults.yaml, tomcat/osfamilymap.yaml
---
No.
#97 
Since #97 was never fixed the best solution is to use Tomcat9 on the Debian family and close #97
```
ID: tomcat package installed and service running
Function: service.running
Name: tomcat9
Result: True
Comment: Service tomcat9 is already enabled, and is running
Started: 21:52:26.118312
Duration: 1428.815 ms
Changes:
----------
tomcat9:
True
Summary for local
-------------
Succeeded: 11 (changed=6)
Failed:     0
-------------
Total states run:     11
Total run time:   26.494 s
vagrant@ubuntu1804:~$ systemctl status tomcat9
● tomcat9.service - Apache Tomcat 9 Web Application Server
Loaded: loaded (/lib/systemd/system/tomcat9.service; enabled; vendor preset: enabled)
Active: active (running) since Thu 2020-11-26 21:52:27 UTC; 12s ago
Docs: …
```
=> chore(version): use tomcat9 on ubuntu/debian
